apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: agora-aegean-portfolios-api
  newName: cesarapires/agora-aegean-portfolios
  newTag: df0821fbabe1b52129762dff4fe9c12f6284cbb6
